services:
  # apk tools - preferred
  apk:
    image: ghcr.io/tyhal/crie-dep-apk
    build: apk
  # go native tools - TODO shouldn't be needed
  go:
    image: ghcr.io/tyhal/crie-dep-go
    build: go
  # js tools
  npm:
    image: ghcr.io/tyhal/crie-dep-npm
    build: npm
  # python tools
  pip:
    image: ghcr.io/tyhal/crie-dep-pip
    build: pip
